# PvPManager Configuration File
# -> In Combat: Tag players on PvP and what should happen when they are in combat
# -> Punishments: Set if you want to punish or not a player that logs out while in combat.
# -> Toggle Signs: You can do the same as the command "/pvp" does but by clicking signs. 
# Just write [pvpmanager] on the first line of a sign, make sure you have the permissions to create one.
# -> Newbie Protection: New players on your server will be protected from PvP for the time you define.
# -> PvPTimer: Toggle PvP automatically on the times specified for each world.
# -> World Exclusions: Write the name of worlds where you don't want to use PvPManager. 
# Just delete the examples and write the name of your worlds to disable.
# For a more detailed explanation of each setting go to: 

Config Version: 7
Update Check: true

In Combat:
  Enabled: true
  Time(seconds): 15
  Stop Commands: true
  Disable Fly: true
  Only Tag Attacker: false
  Punishments:
    Enabled: true
    Broadcast PvPLog: true
    Kill on Logout:
      Enabled: true      
      Keep Items: false
      Keep Exp: false
  
Toggle Signs:
  Enabled: false
  Disable Toggle Command: true
    
Newbie Protection:
  Enabled: true
  Time(minutes): 5
  
PvP Timer:
  Enabled: true
  Announce On World Change: true
  Sound:
    Enabled: true
    PvP Off Sound: SUCCESSFUL_HIT
    PvP On Sound: GHAST_FIREBALL

World Exclusions:
  - Example
  - Example2