# +--------------------------------------------------------------------------+ #
# <                     PvPManager Configuration File                        > #
# <--------------------------------------------------------------------------> #
# <         For a more detailed explanation of each setting go to            > #
# <   http://dev.bukkit.org/bukkit-plugins/pvpmanager/pages/configuration/   > #
# +--------------------------------------------------------------------------+ #

# Informs PvPManager if the config is updated, do not touch it unless you want to reset the config
Config Version: 10

# Should blood animation on PvP be enabled
PvP Blood: true

# What should be disabled on PvP
Disable Fly: true
Disable GameMode: true

# This section defines everything that will happen when a player is tagged in combat
# Time(seconds) - For how many seconds should the player be tagged
# Stop Commands - Should commands be blocked in combat(Example - To prevent teleports)
# -> Allowed Commands - All commands will be blocked except the ones here
# Punishments - When player logs out in combat (PvP log), should he be punished?
# -> Broadcast PvPLog - Broadcast to all the players when someone PvP logs
# -> Fine - Take money from player when he PvP logs (needs Vault)
In Combat:
  Enabled: true
  Time(seconds): 15
  Only Tag Attacker: false
  Stop Commands:
    Enabled: true
    Allowed Commands:
      - tell
      - money
  Punishments:
    Enabled: true
    Broadcast PvPLog: true
    Kill on Logout: true
    Drops:
      Inventory: true
      Experience: true
      Armor: true
    Fine:
      Enabled: false
      Amount: 10.0

# Section for PvP Toggle command(/pvp)
# Cooldown(seconds) - How many seconds players have to wait until they can use /pvp again
PvP Toggle:
  Cooldown(seconds): 30

# Should toggle PvP signs be enabled? (Similar to /pvp command but by clicking signs)
# To create a toggle sign write [pvpmanager] on the first line (remember you need the right permission)
# Disable Toggle Command - Should /pvp command be disabled in order to force using of signs by players?
Toggle Signs:
  Enabled: true
  Disable Toggle Command: false

# Should new players on your server be protected from PvP (If they want to PvP just use /pvp disable protection)
# Time(minutes) - If so, for how many minutes should protection last
Newbie Protection:
  Enabled: true
  Time(minutes): 5

# Should PvPManager be allowed to check for updates and tell you about them
# Auto Update - After checking should we download it automatically for you?
Update Check:
  Enabled: true
  Auto Update: true

# In these worlds PvPManager will not have any effect
World Exclusions:
  - Example
  - Example2
