name: PvPManager
main: me.NoChance.PvPManager.PvPManager
version: 1.2
author: NoChance20
description: Allows Administrators To Change Their PvP Mechanics.

commands:
   pm:
      description: Shows Main PvPManager Page.
   pvp:
      description: Main PvP Status command.
   pvp on:
      description: Enables PvP for yourself.
   pvp off:
      description: Disables PvP for yourself.
   pvp status:
      description: Allows you to check your current PvP status.
   pm reload:
      description: Reloads PvPManager.

permissions:
   pvpmanager.*:
     description: Gives access to all PvPManager features
     default: op
     children:
       pvpmanager.reload: true
       pvpmanager.pvpstatus.change: true
       pvpmanager.pvpstatus.self: true
       pvpmanager.pvpstatus.others: true
       pvpmanager.pvptimer: true
       pvpmanager.sign: true
       pvpmanager.override: true
   pvpmanager.admin:
     description: Gives access to PvPManager features
     default: false
     children:
       pvpmanager.reload: true
       pvpmanager.pvpstatus.change: true
       pvpmanager.pvpstatus.self: true
       pvpmanager.pvpstatus.others: true
       pvpmanager.pvptimer: true
       pvpmanager.sign: true
   pvpmanager.user:
     description: Gives access to PvPManager features that i think would be appropriate for a user
     default: false
     children:
       pvpmanager.pvpstatus.change: true
       pvpmanager.pvpstatus.self: true
       pvpmanager.pvpstatus.others: true
   pvpmanager.pvpstatus.change:
     description: Allows you to change your PvP status between <on> and <off>
     default: false
   pvpmanager.pvpstatus.self:
     description: Allows you to check your current PvP status
     default: false
   pvpmanager.pvpstatus.others:
     description: Allows you to check other players PvP status
     default: false
   pvpmanager.reload:
     description: Allows you to reload PvPManager
     default: false
   pvpmanager.pvptimer:
     description: Allows setting PvP start and end times on worlds
     default: false  
   pvpmanager.sign:
     description: Allows creating PvPManager signs
     default: false
   pvpmanager.override:
     description: Enables a player to override PvP being off in a world
     default: false