name: PvPManager
main: me.NoChance.PvPManager.PvPManager
version: 1.1
author: NoChance20
description: Allows Administrators To Change Their PvP Mechanics.

commands:
   pm:
      description: Shows Main PvPManager Page.
   pvp:
      description: Main PvP Status command.
   pvp on:
      description: Enables PvP for yourself.
   pvp off:
      description: Disables PvP for yourself.
   pvp status:
      description: Allows you to check your current PvP status.
   pm reload:
      description: Reloads PvPManager.

permissions:
   pvpmanager.*:
     description: Gives access to all PvPManager commands
     default: op
     children:
       pvpmanager.reload: true
       pvpmanager.pvpstatus.change: true
       pvpmanager.pvpstatus.self: true
       pvpmanager.pvpstatus.others: true
   pvpmanager.pvpstatus.change:
     description: Allows you to change your PvP status between <on> and <off>
     default: false
   pvpmanager.pvpstatus.self:
     description: Allows you to check your current PvP status
     default: false
   pvpmanager.pvpstatus.others:
     description: Allows you to check other players PvP status
     default: false
   pvpmanager.reload:
     description: Allows you to reload PvPManager
     default: false